### ISSUE TITLE
participant number

### ISSUE THREAD

**Issue by brittaz** [smpo/socialmedia#1]
Hello,
I have trouble adjusting the social media ostracism paradigm. I would like to start a survey where participants are randomly selected into the exclusion or inclusion condition. I could not figure out how to transfer the participant number to the smpo and after the experiment back to the survey for follow up questions (so it would be possible to match pre-experimental answers to post-experimental answers). I am using unipark as a survey software. Is there anyone who could help, please?
regards
Britta

**Comment by smpo** [comment]
Hello Britta, on the [documentation page](http://smpo.github.io/socialmedia/) it is described how to set participants number, and condition as URL parameters. If you want to use unipark for survey questions, you should look up in their documentation how to pass parameters on to their service as URL parameters.
