### ISSUE TITLE
number of profiles

### ISSUE THREAD

**Issue by socialpsy** [smpo/socialmedia#2]
hi, i had a question about this paradigm. I wanted to change the number of profiles that displayed, i.e. the number of virtual confederates the participants interact with (note: I was able to change the number of profile pictures the participant chooses from but not the number of profiles displayed). Could anyone help me with this? Thanks!!

**Comment by smpo** [comment]
You do it by adding another object to the "posts" array in profiles.json. The experiment will have as many profiles as there are objects in this array. Each object has the following structure, which you can copy and paste to add new objects:

      {
        "avatar": "URL",
        "username": "NAME",
        "text": "TEXT",
        "likes": 
      }

This should work. Let me know if it doesn't. 

Greetings,
Ana

**Comment by socialpsy** [comment]
Thanks Ana. This is extremely helpful!
