### ISSUE TITLE
smpo and media lab

### ISSUE THREAD

**Issue by JDedvukaj94** [smpo/socialmedia#3]
Hello, my name is Joseph. I am an undergraduate student. I am having some difficulty in using the smpo I am trying to program it on a social psychology software called MediaLab. For some reason its not running smoothly (errors, unknown faceless characters, off center)  as it would run from a simple web page on Internet explorer or Google Chrome. Are you at all able to assist me in programming it efficiently? I also was wondering if it is possible to program the smpo to eliminate the feature where it must be redirected to a Qualtrics survey. Thank you

**Comment by smpo** [comment]
Hi Joseph, I am not familiar with MediaLab. The issue you describe is a problem with MediaLab's embedding. Maybe they have support forums, where you can find help.

**Comment by JDedvukaj94** [comment]
Okay I will try it. Thank you. Can you also help with my other question. Is it possible to program the smpo without the redirection to a Qualtrics survey. Essentially, eliminate it all together. 

----- Original Message -----

**Comment by smpo** [comment]
Sure. For that you will just need to remove or uncomment the redirection in `main.js` (that is, the line with   `location.href = ...`).

**Comment by JDedvukaj94** [comment]
Perfect. Thank you so much.
