### ISSUE TITLE
embedding the paradigm in a qualtrics survey

### ISSUE THREAD

**Issue by socialpsy** [smpo/socialmedia#4]
Hello, I was hoping to embed this paradigm in the middle of my survey - so I'll have some questions before and after the paradigm. Would you know how to set this up?

I found information on your webpage about how to redirect participants to a survey after the paradigm; however that wouldn't give me a chance to ask questions beforehand. 

Thanks!!

**Comment by jan-matthis** [comment]
Please refer to the qualtrics documentation.
