### ISSUE TITLE
Vraag online paradigm

### ISSUE THREAD

**Issue by evelien77** [smpo/socialmedia#5]
Hallo,

Voor onze bachelor thesis zijn wij bezig met een onderzoek over online uitsluiting. Hiervoor gebruiken we de game die jullie hebben opgezet. Deze hebben wij aangepast en in onze survey gevoegd. Nou hebben wij een dringende vraag; Hoe kunnen wij de game het beste verwerken in onze enquete? Wij zouden het liefst 1 link willen gebruiken voor zowel inclusie als exclusie, en dat het programma het zelf randomiseert. Heeft u een oplossing hoe wij dit het beste kunnen gebruiken?

Gr.

**Comment by smpo** [comment]
Now try in English and maybe we'll be able to help out : )

**Comment by evelien77** [comment]
Im so sorry, I thought you were dutch. First of all, thanks for making the
online paradigm, its really nice. For our bachelor essay, were using the
social media ostracism paradigm our own experiment and we customized it,
changed the time and translated it in dutch etc. We also have a survey
after the group task, but we want 2 conditions, one for exclusion and one
for inclusion, how can we manage that? We made 2 different links for it but
thats impossible because we would like to share one link where the game
automatically determines who gets included and who gets excluded.. Is that
impossible or do you have an idea to fix it?

Hope to hear from you soon!



2015-05-07 14:44 GMT+02:00 smpo <notifications@github.com>:

**Comment by evelien77** [comment]
Im so sorry, I thought you were dutch. First of all, thanks for making the
online paradigm, its really nice. For our bachelor essay, were using the
social media ostracism paradigm our own experiment and we customized it,
changed the time and translated it in dutch etc. We also have a survey
after the group task, but we want 2 conditions, one for exclusion and one
for inclusion, how can we manage that? We made 2 different links for it but
thats impossible because we would like to share one link where the game
automatically determines who gets included and who gets excluded.. Is that
impossible or do you have an idea to fix it?

Hope to hear from you soon!

2015-05-07 14:44 GMT+02:00 smpo notifications@github.com:

**Comment by jan-matthis** [comment]
You could redirect to two different versions of the paradigm from the survey.
