### ISSUE TITLE
Problems with qualtrics, the URL when using the ostracism paradigm 

### ISSUE THREAD

**Issue by TomReurts** [smpo/socialmedia#7]
Dear Ana,

My question is.

How can I start with questions in qualtrics. Then rondomize participants to the two conditions (C=1 and C=2), and then when the paradigm has ended redirect the participant to the next follow up questions in my qualtrics questionaire.

This is the link to my questionaire: 

https://vuass.eu.qualtrics.com/SE/?SID=SV_3dB4aDH6CvyDxSR

Another thing i could do is skip the intro in my qualtrics questionaire. Put only follow-up questions in my qualtrics questionaire.

But when i want to do that the first problem I have is that the redirection doesn’t work because it says there is a wrong URL. I have used these links:

Condition 1 met pp

http://smpo.github.io/preview/index.html?c=1&p=YY&redirect= https%3A%2F%2Fvuass.eu.qualtrics.com%2FSE%2F%3FSID%3DSV_3dB4aDH6CvyDxSR%20

conditie 2 met pp

http://smpo.github.io/preview/index.html?c=2&p=YY&redirect= https%3A%2F%2Fvuass.eu.qualtrics.com%2FSE%2F%3FSID%3DSV_3dB4aDH6CvyDxSR%20

Another issue here is the p=YY, I want this to go automatically. In the example on the website it looks like you have to do it manually and provide every participant with an unique link.

Do you know an easy way how to handle these problems?

Your help will be very much appreciated.

Yours sincerely Tom Reurts  1774840. tel: 0031-649125579

**Comment by jan-matthis** [comment]
For question 1: The problem seems to be with your url encoding. You would need to remove the '%20' from the end of the url. 

Question 2 is outside the scope, please refer to the Qualtrics documentation instead.
